// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.github.janmichaelpeter.window_placement

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * The app window and the display it is on, in logical pixels and display
 * coordinates.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WindowGeometry (
  val windowX: Double,
  val windowY: Double,
  val windowWidth: Double,
  val windowHeight: Double,
  val screenWidth: Double,
  val screenHeight: Double,
  /**
   * System bars / cutouts on each side of the display that a docked window
   * may stop at. Zero where the platform has none.
   */
  val screenInsetLeft: Double,
  val screenInsetTop: Double,
  val screenInsetRight: Double,
  val screenInsetBottom: Double,
  /** Whether the OS reports the app as being in a multi-window mode. */
  val isMultiWindow: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WindowGeometry {
      val windowX = pigeonVar_list[0] as Double
      val windowY = pigeonVar_list[1] as Double
      val windowWidth = pigeonVar_list[2] as Double
      val windowHeight = pigeonVar_list[3] as Double
      val screenWidth = pigeonVar_list[4] as Double
      val screenHeight = pigeonVar_list[5] as Double
      val screenInsetLeft = pigeonVar_list[6] as Double
      val screenInsetTop = pigeonVar_list[7] as Double
      val screenInsetRight = pigeonVar_list[8] as Double
      val screenInsetBottom = pigeonVar_list[9] as Double
      val isMultiWindow = pigeonVar_list[10] as Boolean
      return WindowGeometry(windowX, windowY, windowWidth, windowHeight, screenWidth, screenHeight, screenInsetLeft, screenInsetTop, screenInsetRight, screenInsetBottom, isMultiWindow)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      windowX,
      windowY,
      windowWidth,
      windowHeight,
      screenWidth,
      screenHeight,
      screenInsetLeft,
      screenInsetTop,
      screenInsetRight,
      screenInsetBottom,
      isMultiWindow,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WindowGeometry
    return MessagesPigeonUtils.deepEquals(this.windowX, other.windowX) && MessagesPigeonUtils.deepEquals(this.windowY, other.windowY) && MessagesPigeonUtils.deepEquals(this.windowWidth, other.windowWidth) && MessagesPigeonUtils.deepEquals(this.windowHeight, other.windowHeight) && MessagesPigeonUtils.deepEquals(this.screenWidth, other.screenWidth) && MessagesPigeonUtils.deepEquals(this.screenHeight, other.screenHeight) && MessagesPigeonUtils.deepEquals(this.screenInsetLeft, other.screenInsetLeft) && MessagesPigeonUtils.deepEquals(this.screenInsetTop, other.screenInsetTop) && MessagesPigeonUtils.deepEquals(this.screenInsetRight, other.screenInsetRight) && MessagesPigeonUtils.deepEquals(this.screenInsetBottom, other.screenInsetBottom) && MessagesPigeonUtils.deepEquals(this.isMultiWindow, other.isMultiWindow)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.windowX)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.windowY)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.windowWidth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.windowHeight)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.screenWidth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.screenHeight)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.screenInsetLeft)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.screenInsetTop)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.screenInsetRight)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.screenInsetBottom)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isMultiWindow)
    return result
  }
  override fun toString(): String {
    return "WindowGeometry(windowX=$windowX, windowY=$windowY, windowWidth=$windowWidth, windowHeight=$windowHeight, screenWidth=$screenWidth, screenHeight=$screenHeight, screenInsetLeft=$screenInsetLeft, screenInsetTop=$screenInsetTop, screenInsetRight=$screenInsetRight, screenInsetBottom=$screenInsetBottom, isMultiWindow=$isMultiWindow)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WindowGeometry.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is WindowGeometry -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WindowPlacementHostApi {
  /** The current geometry, or null when no window is attached yet. */
  fun getGeometry(): WindowGeometry?

  companion object {
    /** The codec used by WindowPlacementHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `WindowPlacementHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WindowPlacementHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.window_placement.WindowPlacementHostApi.getGeometry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getGeometry())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class GeometryChangesStreamHandler : MessagesPigeonEventChannelWrapper<WindowGeometry> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: GeometryChangesStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.window_placement.WindowPlacementEventApi.geometryChanges"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<WindowGeometry>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<WindowGeometry>) {}

override fun onCancel(p0: Any?) {}
}
      
