// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// The app window and the display it is on, in logical pixels and display
/// coordinates.
class WindowGeometry {
  WindowGeometry({
    required this.windowX,
    required this.windowY,
    required this.windowWidth,
    required this.windowHeight,
    required this.screenWidth,
    required this.screenHeight,
    required this.screenInsetLeft,
    required this.screenInsetTop,
    required this.screenInsetRight,
    required this.screenInsetBottom,
    required this.isMultiWindow,
  });

  double windowX;

  double windowY;

  double windowWidth;

  double windowHeight;

  double screenWidth;

  double screenHeight;

  /// System bars / cutouts on each side of the display that a docked window
  /// may stop at. Zero where the platform has none.
  double screenInsetLeft;

  double screenInsetTop;

  double screenInsetRight;

  double screenInsetBottom;

  /// Whether the OS reports the app as being in a multi-window mode.
  bool isMultiWindow;

  List<Object?> _toList() {
    return <Object?>[
      windowX,
      windowY,
      windowWidth,
      windowHeight,
      screenWidth,
      screenHeight,
      screenInsetLeft,
      screenInsetTop,
      screenInsetRight,
      screenInsetBottom,
      isMultiWindow,
    ];
  }

  Object encode() {
    return _toList();  }

  static WindowGeometry decode(Object result) {
    result as List<Object?>;
    return WindowGeometry(
      windowX: result[0]! as double,
      windowY: result[1]! as double,
      windowWidth: result[2]! as double,
      windowHeight: result[3]! as double,
      screenWidth: result[4]! as double,
      screenHeight: result[5]! as double,
      screenInsetLeft: result[6]! as double,
      screenInsetTop: result[7]! as double,
      screenInsetRight: result[8]! as double,
      screenInsetBottom: result[9]! as double,
      isMultiWindow: result[10]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WindowGeometry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(windowX, other.windowX) && _deepEquals(windowY, other.windowY) && _deepEquals(windowWidth, other.windowWidth) && _deepEquals(windowHeight, other.windowHeight) && _deepEquals(screenWidth, other.screenWidth) && _deepEquals(screenHeight, other.screenHeight) && _deepEquals(screenInsetLeft, other.screenInsetLeft) && _deepEquals(screenInsetTop, other.screenInsetTop) && _deepEquals(screenInsetRight, other.screenInsetRight) && _deepEquals(screenInsetBottom, other.screenInsetBottom) && _deepEquals(isMultiWindow, other.isMultiWindow);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WindowGeometry(windowX: $windowX, windowY: $windowY, windowWidth: $windowWidth, windowHeight: $windowHeight, screenWidth: $screenWidth, screenHeight: $screenHeight, screenInsetLeft: $screenInsetLeft, screenInsetTop: $screenInsetTop, screenInsetRight: $screenInsetRight, screenInsetBottom: $screenInsetBottom, isMultiWindow: $isMultiWindow)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is WindowGeometry) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return WindowGeometry.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class WindowPlacementHostApi {
  /// Constructor for [WindowPlacementHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WindowPlacementHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// The current geometry, or null when no window is attached yet.
  Future<WindowGeometry?> getGeometry() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.window_placement.WindowPlacementHostApi.getGeometry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as WindowGeometry?;
  }
}

/// Emits the geometry on listen and whenever it changes.
///
/// Returns a broadcast [Stream] of events from the `geometryChanges` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<WindowGeometry> geometryChanges( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel geometryChangesChannel =
      EventChannel('dev.flutter.pigeon.window_placement.WindowPlacementEventApi.geometryChanges$instanceName', pigeonMethodCodec);
  return geometryChangesChannel.receiveBroadcastStream().map((dynamic event) {
    return event as WindowGeometry;
  });
}
    
