// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// The app window and the display it is on, in logical pixels and display
/// coordinates.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WindowGeometry: Hashable, CustomStringConvertible {
  var windowX: Double
  var windowY: Double
  var windowWidth: Double
  var windowHeight: Double
  var screenWidth: Double
  var screenHeight: Double
  /// System bars / cutouts on each side of the display that a docked window
  /// may stop at. Zero where the platform has none.
  var screenInsetLeft: Double
  var screenInsetTop: Double
  var screenInsetRight: Double
  var screenInsetBottom: Double
  /// Whether the OS reports the app as being in a multi-window mode.
  var isMultiWindow: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WindowGeometry? {
    let windowX = pigeonVar_list[0] as! Double
    let windowY = pigeonVar_list[1] as! Double
    let windowWidth = pigeonVar_list[2] as! Double
    let windowHeight = pigeonVar_list[3] as! Double
    let screenWidth = pigeonVar_list[4] as! Double
    let screenHeight = pigeonVar_list[5] as! Double
    let screenInsetLeft = pigeonVar_list[6] as! Double
    let screenInsetTop = pigeonVar_list[7] as! Double
    let screenInsetRight = pigeonVar_list[8] as! Double
    let screenInsetBottom = pigeonVar_list[9] as! Double
    let isMultiWindow = pigeonVar_list[10] as! Bool

    return WindowGeometry(
      windowX: windowX,
      windowY: windowY,
      windowWidth: windowWidth,
      windowHeight: windowHeight,
      screenWidth: screenWidth,
      screenHeight: screenHeight,
      screenInsetLeft: screenInsetLeft,
      screenInsetTop: screenInsetTop,
      screenInsetRight: screenInsetRight,
      screenInsetBottom: screenInsetBottom,
      isMultiWindow: isMultiWindow
    )
  }
  func toList() -> [Any?] {
    return [
      windowX,
      windowY,
      windowWidth,
      windowHeight,
      screenWidth,
      screenHeight,
      screenInsetLeft,
      screenInsetTop,
      screenInsetRight,
      screenInsetBottom,
      isMultiWindow,
    ]
  }
  static func == (lhs: WindowGeometry, rhs: WindowGeometry) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.windowX, rhs.windowX) && MessagesPigeonInternal.deepEquals(lhs.windowY, rhs.windowY) && MessagesPigeonInternal.deepEquals(lhs.windowWidth, rhs.windowWidth) && MessagesPigeonInternal.deepEquals(lhs.windowHeight, rhs.windowHeight) && MessagesPigeonInternal.deepEquals(lhs.screenWidth, rhs.screenWidth) && MessagesPigeonInternal.deepEquals(lhs.screenHeight, rhs.screenHeight) && MessagesPigeonInternal.deepEquals(lhs.screenInsetLeft, rhs.screenInsetLeft) && MessagesPigeonInternal.deepEquals(lhs.screenInsetTop, rhs.screenInsetTop) && MessagesPigeonInternal.deepEquals(lhs.screenInsetRight, rhs.screenInsetRight) && MessagesPigeonInternal.deepEquals(lhs.screenInsetBottom, rhs.screenInsetBottom) && MessagesPigeonInternal.deepEquals(lhs.isMultiWindow, rhs.isMultiWindow)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WindowGeometry")
    MessagesPigeonInternal.deepHash(value: windowX, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: windowY, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: windowWidth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: windowHeight, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: screenWidth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: screenHeight, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: screenInsetLeft, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: screenInsetTop, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: screenInsetRight, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: screenInsetBottom, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isMultiWindow, hasher: &hasher)
  }

  public var description: String {
    return "WindowGeometry(windowX: \(String(describing: windowX)), windowY: \(String(describing: windowY)), windowWidth: \(String(describing: windowWidth)), windowHeight: \(String(describing: windowHeight)), screenWidth: \(String(describing: screenWidth)), screenHeight: \(String(describing: screenHeight)), screenInsetLeft: \(String(describing: screenInsetLeft)), screenInsetTop: \(String(describing: screenInsetTop)), screenInsetRight: \(String(describing: screenInsetRight)), screenInsetBottom: \(String(describing: screenInsetBottom)), isMultiWindow: \(String(describing: isMultiWindow)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return WindowGeometry.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WindowGeometry {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WindowPlacementHostApi {
  /// The current geometry, or null when no window is attached yet.
  func getGeometry() throws -> WindowGeometry?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WindowPlacementHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `WindowPlacementHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WindowPlacementHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// The current geometry, or null when no window is attached yet.
    let getGeometryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.window_placement.WindowPlacementHostApi.getGeometry\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getGeometryChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getGeometry()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getGeometryChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class GeometryChangesStreamHandler: PigeonEventChannelWrapper<WindowGeometry> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: GeometryChangesStreamHandler) {
    var channelName = "dev.flutter.pigeon.window_placement.WindowPlacementEventApi.geometryChanges"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<WindowGeometry>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
